# Generated by Django 5.2.13 on 2026-04-30 23:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('id_produto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('quantidade_estoque', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidade_medida', models.CharField(max_length=30)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rebanho',
            fields=[
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('id_rebanho', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('quantidade_animais', models.PositiveIntegerField(default=0)),
                ('tipo_criacao', models.CharField(max_length=80)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rebanho',
                'verbose_name_plural': 'Rebanhos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('id_talhao', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('localizacao', models.CharField(max_length=180)),
                ('capacidade', models.PositiveIntegerField(default=0)),
                ('area_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Talhao',
                'verbose_name_plural': 'Talhoes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Admin'), ('USUARIO', 'Usuario')], default='USUARIO', max_length=20)),
                ('permissao', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('id_animal', models.BigAutoField(primary_key=True, serialize=False)),
                ('identificacao', models.CharField(max_length=80, unique=True)),
                ('raca', models.CharField(max_length=80)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Femea', 'Femea')], max_length=10)),
                ('idade', models.PositiveIntegerField(default=0)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('status_saude', models.CharField(choices=[('Saudavel', 'Saudavel'), ('Observacao', 'Observacao'), ('Tratamento', 'Tratamento'), ('Critico', 'Critico')], default='Saudavel', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('rebanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animais', to='rebanho.rebanho')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['identificacao'],
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('id_alimento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=80)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_fornecimento', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alimentos', to='rebanho.produto')),
                ('rebanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alimentos', to='rebanho.rebanho')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
                'ordering': ['-data_fornecimento', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Sanidade',
            fields=[
                ('id_sanidade', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_registro', models.DateField()),
                ('status_sanitario', models.CharField(choices=[('Saudavel', 'Saudavel'), ('Em observacao', 'Em observacao'), ('Em tratamento', 'Em tratamento'), ('Critico', 'Critico')], default='Saudavel', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanidades', to='rebanho.animal')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanidades_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sanidade',
                'verbose_name_plural': 'Sanidades',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('dosagem', models.CharField(blank=True, max_length=80)),
                ('periodo_tratamento', models.CharField(blank=True, max_length=120)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('sanidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='rebanho.sanidade')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['-data_inicio', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id_exame', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(blank=True, max_length=80)),
                ('data_realizacao', models.DateField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('observacoes', models.TextField(blank=True)),
                ('sanidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='rebanho.sanidade')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'ordering': ['-data_realizacao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Enfermidade',
            fields=[
                ('id_enfermidade', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('data_diagnostico', models.DateField(blank=True, null=True)),
                ('gravidade', models.CharField(blank=True, max_length=80)),
                ('status_tratamento', models.CharField(blank=True, max_length=80)),
                ('observacoes', models.TextField(blank=True)),
                ('sanidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermidades', to='rebanho.sanidade')),
            ],
            options={
                'verbose_name': 'Enfermidade',
                'verbose_name_plural': 'Enfermidades',
                'ordering': ['-data_diagnostico', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='rebanho',
            name='talhao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rebanho', to='rebanho.talhao'),
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id_vacina', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('dose', models.CharField(blank=True, max_length=80)),
                ('data_aplicacao', models.DateField(blank=True, null=True)),
                ('proxima_dose', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('observacoes', models.TextField(blank=True)),
                ('sanidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='rebanho.sanidade')),
            ],
            options={
                'verbose_name': 'Vacina',
                'verbose_name_plural': 'Vacinas',
                'ordering': ['-data_aplicacao', 'nome'],
            },
        ),
    ]
