# Generated by Django 6.0.6 on 2026-06-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebanho', '0002_seed_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rebanho',
            name='quantidade_animais',
        ),
    ]
