# Generated by Django 6.0.6 on 2026-06-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebanho', '0003_remove_quantidade_animais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='idade',
        ),
    ]
